#!/usr/bin/env bash
# Phase 2 — Deploy Quadlet unit and start the server for the first time
# Run as root on the Raspberry Pi 4:
#   sudo bash scripts/02-deploy.sh
# ---------------------------------------------------------------------------
set -euo pipefail

source "$(dirname "$0")/config.env"

info()  { echo -e "\033[1;34m[INFO]\033[0m  $*"; }
ok()    { echo -e "\033[1;32m[ OK ]\033[0m  $*"; }
die()   { echo -e "\033[1;31m[FAIL]\033[0m  $*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "This script must be run as root (sudo bash $0)"
[[ -d "$DATA_DIR" ]] || die "$DATA_DIR does not exist. Run 01-system-setup.sh first."

# ── 1. Copy plugins.txt into data directory ─────────────────────────────────
info "Copying plugins.txt → $DATA_DIR/plugins.txt"
cp "$REPO_DIR/plugins.txt" "$DATA_DIR/plugins.txt"
ok "plugins.txt deployed"

# ── 2. Install Quadlet unit ─────────────────────────────────────────────────
info "Installing Quadlet container unit (data path: $DATA_DIR)..."
mkdir -p "$QUADLET_DIR"
sed "s|/opt/minecraft/data|${DATA_DIR}|g" \
    "$REPO_DIR/systemd/minecraft.container" \
    > "$QUADLET_DIR/minecraft.container"
ok "Quadlet unit installed at $QUADLET_DIR/minecraft.container"

# ── 3. Reload systemd — Quadlet generator creates minecraft.service ─────────
info "Reloading systemd daemon (Quadlet generator runs here)..."
systemctl daemon-reload

# Confirm the generated service appeared
if ! systemctl cat minecraft.service &>/dev/null; then
    die "minecraft.service was not generated. Check Quadlet unit syntax with:\n" \
        "  /usr/lib/systemd/system-generators/podman-system-generator --dryrun"
fi
ok "minecraft.service generated by Quadlet"

# ── 4. Pull image in advance (avoids timeout on first start) ────────────────
info "Pre-pulling docker.io/itzg/minecraft-server:java21 (ARM64)..."
podman pull docker.io/itzg/minecraft-server:java21
ok "Image pulled"

# ── 5. Enable and start ─────────────────────────────────────────────────────
info "Enabling and starting minecraft.service..."
systemctl enable minecraft.service
systemctl start minecraft.service

echo ""
echo "──────────────────────────────────────────────────────────────"
ok "Server is starting. First run downloads Purpur + all plugins."
echo ""
echo "  Watch progress:"
echo "    journalctl -fu minecraft.service"
echo ""
echo "  The server is ready when you see:"
echo "    Done (Xs)! For help, type \"help\""
echo ""
echo "  Once ready, run Phase 3 to apply performance optimisations:"
echo "    sudo bash scripts/03-apply-configs.sh"
echo "──────────────────────────────────────────────────────────────"
